bolshakov/stoplight

CHANGELOG.md, README.md, bench/memory_bench.rb, bench/redis_bench.rb, lib/stoplight.rb, spec/stoplight_spec.rb
This pull request creates a `Stoplight` helper function that acts as an alias for `Stoplight::Light.new`. This is purely for convenience and doesn't add any new functionality.
``` rb
Stoplight::Light.new('example') { nil }.run
Stoplight('example') { nil }.run
```
I got the idea from [circuit_b](https://github.com/alg/circuit_b/tree/1.1#usage). I'm not convinced that `Stoplight` is the right name for this function. Some other options include:
- `stoplight`: This seems like it would often conflict with a local variable. 
- `Stoplight.light`: This has the benefit of existing within the stoplight module, but it's still a little verbose.
=> Create a helper function for creating stoplights

.travis.yml
Fixes #75. 
This fixes the Rubinius build by only running RuboCop on MRI. Furthermore, it only runs RuboCop *once* instead of 6 times.
=> Fix Rubinius build on Travis CI

CHANGELOG.md, README.md, lib/stoplight.rb, lib/stoplight/notifier/honeybadger.rb, spec/stoplight/notifier/honeybadger_spec.rb, stoplight.gemspec
This pull request fixes #79. It adds a notifier for the Honeybadger error reporting service.
=> Add a Honeybadger notifier

spec/stoplight/notifier/bugsnag_spec.rb, spec/stoplight/notifier/hip_chat_spec.rb, spec/stoplight/notifier/honeybadger_spec.rb, spec/stoplight/notifier/logger_spec.rb, spec/stoplight/notifier/slack_spec.rb
This pull request aims to fix #83. It does so by not requiring the gems that power the notifiers. Since the specs stub them out anyway, they aren't really necessary.
=> Don't unnecessarily import gems

README.md, lib/stoplight/default.rb, lib/stoplight/light.rb, lib/stoplight/light/runnable.rb, spec/stoplight/default_spec.rb, spec/stoplight/light/runnable_spec.rb, spec/stoplight/light_spec.rb
I've come across a situation where I would only like one or two types of errors to change the state of the stoplight. Currently, I would have to use the `.with_allowed_errors` method to whitelist all the other errors that could potentially occur. This adds a `.with_blacklisted_errors` method that essentially does the opposite. You can specify error classes that should affect the stoplight state, and all other errors will be raised normally.
It's important to note a couple things:
- If `blacklisted_errors` is empty (which is the default), the stoplight will behave the same way it currently does
- If an error is both allowed and blacklisted, it will not affect the state of the stoplight—`allowed_errors` takes precedence over `blacklisted_errors`
=> Add blacklisted errors option

lib/stoplight/light/runnable.rb, spec/stoplight/light/runnable_spec.rb
When blacklisting an error that inherited from Exception Class Stoplight would fail to rescue this error because it only rescues StandardError. The proposed solution is to rescue from any blacklisted_errors, in addition to StandardError.
=> Rescues all blacklisted errors

README.md, lib/stoplight/default.rb, lib/stoplight/error.rb, lib/stoplight/light.rb, lib/stoplight/light/runnable.rb, spec/stoplight/default_spec.rb, spec/stoplight/light/runnable_spec.rb, spec/stoplight/light_spec.rb
This will fix #91. It still needs some tests.
=> Replace white/blacklists with error handler

lib/stoplight/failure.rb, lib/stoplight/light/runnable.rb
ActiveSupport::Testing::TimeHelpers stubs `Time.now` automatically, so Timecop
won't be a required dependency when testing Stoplight inside of a gem
consumer's project.
------
Thanks for making this gem! If you have any specific contributor guidelines that I haven't followed, just let me know.
=> Add support ActiveSupport::Testing::TimeHelpers

lib/stoplight/data_store/memory.rb, stoplight.gemspec
`concurrent-ruby` isn't needed just to do thread safe hashes. Prompted by this memory profile where including the gem is adding almost `6MB` at startup:
```
stoplight: 5.8203 MiB
stoplight/data_store/memory: 5.293 MiB
concurrent: 5.2383 MiB
concurrent/executors: 1.3906 MiB
concurrent/executor/timer_set: 0.6953 MiB
concurrent/scheduled_task: 0.4844 MiB (Also required by: concurrent, concurrent/timer_task)
concurrent/ivar: 0.3047 MiB (Also required by: concurrent/async, concurrent/future, and 2 others)
concurrent/configuration: 1.3203 MiB (Also required by: concurrent/scheduled_task, concurrent/options, and 2 others)
concurrent/delay: 0.8789 MiB (Also required by: concurrent/utility/processor_counter, concurrent)
concurrent/concern/obligation: 0.7031 MiB (Also required by: concurrent/ivar) …
```
=> Replace concurrent-ruby with MonitorMixin

lib/stoplight/data_store/redis.rb, spec/stoplight/data_store/memory_spec.rb, spec/stoplight/data_store/redis_spec.rb
Light names containing colons lead to names returned by `data_store.names` to be incomplete
eg. `Stoplight('http://api.example.com/some/action')` and `names` will return `['//api.example.com/some/action']`. 
This leads to a misleading representation of the current state on [stoplight-admin](https://github.com/orgsync/stoplight-admin/blob/master/lib/sinatra/stoplight_admin.rb#L24).
=> Support light names containing colons

README.md
This is an awesome tool! Thank you so much. I was going through the readme and noticed this small typo `cool of` should be `cool off`.
=> Fix small readme typo

.travis.yml, spec/stoplight/default_spec.rb
Replacing Fixnum with Integer removes a deprecation warning that you would receive with MRI versions 2.4 and 2.5 respectively but also works fine for 2.1-2.3 versions so I consider this a safe improvement.
I also added 2.4 and 2.5 to the build matrix for travis ci. Also added some indentation to the .travis.yml file where my editor felt that it was in order to do so.
=> Replace Fixnum with Integer in default_spec.rb to eliminate deprecation warning

lib/stoplight/failure.rb, spec/stoplight/failure_spec.rb
When using stoplight together with stoplight-admin, this surfaces when using the `/stats` endpoint when there's a failure.
```
$ bundle exec irn -r redis -r stoplight
redis = Redis.new(host: 'redis')
Stoplight::Light.default_data_store = Stoplight::DataStore::Redis.new(redis)
light = Stoplight('shiny') { 1/0 }
light.run
```
```
$ cat app.rb
require 'redis'
require 'sinatra'
require 'sinatra/stoplight_admin'
require 'webrick'
set :environment, :production
set :bind, '0.0.0.0'
set :port, 8080
set :data_store, Stoplight::DataStore::Redis.new(Redis.new(host: 'redis'))
WEBrick::Utils.su 'nobody'
$ bundle exec ruby app.rb
```
```
$ curl localhost:8080
```
The server will now dump this:
```
2020-05-15 15:00:39 - ArgumentError - wrong number of arguments (given 1, expected 0): …
```
=> Allow Failure#to_json to accept options

lib/stoplight.rb
Following up on https://github.com/bolshakov/stoplight/pull/154. This PR removes the last bit of hipchat that is left in the initializer.
=> Remove hipchat requirement from initializer

.rubocop.yml, spec/spec_helper.rb, spec/stoplight/data_store/memory_spec.rb, spec/stoplight/data_store/redis_spec.rb, spec/support/data_store/base.rb, spec/support/data_store/base/clear_failures.rb, spec/support/data_store/base/clear_state.rb, spec/support/data_store/base/get_all.rb, spec/support/data_store/base/get_failures.rb, spec/support/data_store/base/get_state.rb, spec/support/data_store/base/names.rb, spec/support/data_store/base/record_failures.rb, spec/support/data_store/base/set_state.rb, spec/support/data_store/base/with_notification_lock.rb, stoplight.gemspec
Moved data store specs to use the same specs in the https://github.com/bolshakov/stoplight/pull/165
=> Move data store specs into shared examples

lib/stoplight/data_store/base.rb, lib/stoplight/data_store/memory.rb, lib/stoplight/data_store/redis.rb, spec/support/data_store/base/clear_failures.rb, spec/support/data_store/base/get_all.rb, spec/support/data_store/base/get_failures.rb, spec/support/data_store/base/record_failures.rb
This is the first step toward introducing the running window strategy. I added the `window` parameter to the `get_all`, `get_failures`, `record_failure`, and `clear_failures` methods. It does nothing now, but it will be used to specify the running window size in the future.
I make a few refactoring in the specs to prepare them for future changes. After introducing the running window strategy, we should be able to run the same specs suite.
The rubocop complains about unused parameters, but this is fine because the PR target branch is [feature/running-window](https://github.com/bolshakov/stoplight/tree/feature/running-window), which I'll be using for integrating all the changes related to "running window" effort.
=> Add window parameter to get_all, get_failures, record_failure, and clear_failures methods

lib/stoplight.rb, lib/stoplight/default.rb, lib/stoplight/light.rb, lib/stoplight/light/runnable.rb, lib/stoplight/strategy/base.rb, lib/stoplight/strategy/vintage.rb, spec/spec_helper.rb, spec/stoplight/light/runnable_spec.rb, spec/stoplight/light_spec.rb, spec/stoplight/strategy/base_spec.rb, spec/stoplight/strategy/vintage_spec.rb, spec/support/data_store/base/get_failures.rb, spec/support/strategy/base.rb, spec/support/strategy/base/clear_failures.rb, spec/support/strategy/base/get_all.rb, spec/support/strategy/base/get_failures.rb, spec/support/strategy/base/record_failures.rb, spec/support/strategy/vintage.rb
This second refactoring step aimed to introduce the running window behavior for counting errors. 
The `Stoplight::Strategy::Base:` is the interface that each strategy should implement. The interface is the same as  `Stoplight::DataStore::Base`.
The `Stoplight::Strategy::Vintage` implements the old-fashioned strategy that Stoplight implements today. 
All the `Stoplight::Light#data_store` usages were replaced with `Stoplight::Light#strategy` usages. 
This PR also introduces a breaking change: the public `Stoplight#data_store` accessor is not available anymore (which may affect end users, e.g., stoplight-admin) 
The PR targets the [feature/running-window](https://github.com/bolshakov/stoplight/tree/feature/running-window) branch and I suggest accepting this breaking change for now. Before …
=> Replace data store uses with strategy

spec/support/light/runnable/color.rb, spec/support/light/runnable/run.rb
Before this change, the tests used the same failure instance to test the red and yellow states. Instead of a list, we want to store errors in a set (https://github.com/bolshakov/stoplight/pull/172). 
Each error [serializes](https://github.com/bolshakov/stoplight/blob/master/lib/stoplight/failure.rb#L57) into a JSON string. Thus, storing two instances of the same failure in a set will result in just one instance being saved. So to accommodate these changes, I updated the specs to use different error instances.
=> Do not use the same error instance for tests

README.md, lib/stoplight/light/lockable.rb
This ticket aims to fix documentation for the `Light#lock`, and `Light#unlock` methods.
At the moment, in the documentation, we show that we return a light state instead of light in the `Light#lock` and `Light#unlock` methods. We decided to return the light itself and would like to reflect this in the documentation.
=> Chore | Fix documentation for lockable methods

.github/workflows/specs.yml, .rubocop.yml, Gemfile, Gemfile.lock, README.md, UPGRADING.md, lib/stoplight/version.rb, stoplight.gemspec
The next major release has been published, bringing a number of improvements and new features! However, it also introduces breaking changes. As a result, we removed certain notifiers. However, upgrading from Stoplight 3.x to Stoplight 4.0 need not be difficult. In fact, we have listed all the necessary steps in the [UPGRADING.md] documentation.
We aim to make Stoplight's configuration sharable across the code. The following change, enables Stoplight to run different code blocks with the same configuration:
```ruby
light = Stoplight('http-api').with_cool_off_time(300)
light.run { call_this }
light.run { call_that }
```
The `Stoplight()` returns an immutable `Stoplight::CircuitBreaker` object that can be safely reconfigured. It makes it compatible with various Dependency Injections systems: …
=> Stoplight 4.0 🎉

README.md
We use Honeybadger and Stoplight. We will migrate to the V4 soon so we decide to develop the gem to be able to notify HB. as it's not support anymore with the new version.
=> Add link for Honeybadger Notifiers gem

.rubocop.yml, README.md, lib/stoplight/builder.rb, lib/stoplight/circuit_breaker.rb, lib/stoplight/configuration.rb, lib/stoplight/default.rb, lib/stoplight/error.rb, lib/stoplight/light.rb, lib/stoplight/light/runnable.rb, spec/stoplight/builder_spec.rb, spec/stoplight/circuit_breaker_spec.rb, spec/stoplight/default_spec.rb, spec/stoplight_spec.rb, spec/support/circuit_breaker.rb, spec/support/light/runnable/run.rb
This PR introduces significant improvements to the Stoplight gem API, making it more flexible and easier to use. Note that this is a breaking change that addresses design limitations in the current implementation.
The current approach using `#with_error_handler` and `#with_fallback` creates several problems:
1. **Configuration Leakage**: Both `#with_error_handler` and `#with_fallback` were slightly different from other configuration options, it was possible to define them on the `Stoplight::Light` lever which was a mutable instance. It was implemented this way for the sake of backward compatibility.
```ruby
shared_light = Stoplight("payment")
.with_threshold(5)
.with_fallback { |error| log_and_return_empty_array(error) }
shared_light.with_error_handler { |error, handler| .... l }.run { …
```
=> Improving Configuration and Error Handling

Gemfile, README.md, lib/stoplight.rb, spec/stoplight_spec.rb
In addition to the builder interface, you can directly create a stoplight using the `Stoplight()` method. This method allows you to configure the stoplight with a name and optional settings in a single step.
```ruby
light = Stoplight('example-direct', cool_off_time: 10, threshold: 5)
light.run { 1 / 0 }
light.color
```
The `Stoplight()` method accepts the following settings:
* `:cool_off_time` - The time to wait before resetting the circuit breaker.
* `:data_store` - The data store to use for storing state.
* `:error_notifier` - A proc to handle error notifications.
* `:notifiers` - A list of notifiers to use.
* `:threshold` - The failure threshold to trip the circuit breaker.
* `:window_size` - The size of the rolling window for failure tracking.
* `:tracked_errors` - A list of errors to …
=> Allow passing configuration options to Stoplight() method

Gemfile, Gemfile.lock, bench/data_store/memory/with_deduplicated_notification.rb, lib/stoplight/data_store/memory.rb
The original implementation of `#with_deduplicated_notification` in `Memory` data store was locking the entire data store via MonitorMixin's `synchronize` while yielding to notifiers. Even though notifications are rare in our system, when they do happen, they could potentially block other critical operations.
This change introduces a focused optimization:
1. Separate the notification lock from the main data store lock by using a dedicated `Thread::Mutex` specifically for notifications
2. Move the yield operation outside of the synchronized block to prevent blocking other operations during notification processing
3. Add benchmarks to measure and verify the performance characteristics
Under simulated high contention (10 resource names, 16 threads with 0.001s operations):
- Original …
=> Optimize notification locking for improved responsiveness

.standard.yml, Gemfile, Gemfile.lock, README.md, lib/stoplight/data_store/redis.rb, spec/stoplight/data_store/redis_spec.rb, spec/support/database_cleaner.rb
Adds support for using connection pools with the Redis data store. This allows Stoplight to efficiently manage Redis connections in multi-threaded environments, preventing connection exhaustion in high-traffic applications.
* Added connection_pool gem to development dependencies
* Modified the Redis data store to accept either a direct Redis client or a ConnectionPool instance
* Used `.then` method to safely access the Redis client from either source
* Updated specs to test both direct Redis client and ConnectionPool scenarios
* Added documentation for connection pooling usage
The `Stoplight::DataStore::Redis` class now accepts either a `Redis` client or a `ConnectionPool` of Redis clients in its constructor. It then uses the `.then` method to handle both cases uniformly:
```ruby …
```
=> Add support for Redis connection pooling

Gemfile.lock, lib/stoplight.rb, stoplight.gemspec
It was always a pain to maintain the right order of components loading. With zeitwerk, we don't have to worry about this anymore. It loads the code automatically.
=> Use zeitwerk for code loading

.github/workflows/ci.yml, Gemfile, Gemfile.lock
This reverts commit 7c70f95cd8841033d90933b2bcb5b879145b99fd.
It seems jruby does not work with zeitwerk 
#291
=> Revert "Add Jruby to test suite (#300)"

lib/stoplight.rb, lib/stoplight/config/config_provider.rb, spec/stoplight_spec.rb
This change improves Stoplight initialization performance by approximately 12% by optimizing how configuration settings are merged during object creation.
The performance gain is achived by computing default settings once during `ConfigProvider` initialization instead of merging them on every light creation
Before:
```
Create Before Refactoring: 270,049.2 i/s (3.70 μs/i)
```
After:
```
Create After Refactoring: 301,795.9 i/s (3.31 μs/i)
```
Performance improvement: 12% faster initialization
#285
=> Improve Stoplight initialization performance by optimizing config merging

Gemfile.lock, stoplight.gemspec
This PR aims to fix Gem Spec configuration:
1. We now require `zeitwerk` as a runtime dependency.
2. The minimum supported Ruby version is now 3.2.
=> Fix: Gem Spec configuration

README.md, lib/stoplight/default.rb, lib/stoplight/light/config.rb, lib/stoplight/light/runnable/green_run_strategy.rb, lib/stoplight/light/runnable/yellow_run_strategy.rb
Stoplight is designed to handle transient failures and provide graceful degradation. System-level exceptions like `NoMemoryError`, `SystemExit`, and `SignalException` typically indicate unrecoverable conditions where the application should terminate rather than attempt recovery through fallback logic.
This PR changes Stoplight's behavior to capture only `StandardError` exceptions, simplifying error handling logic and aligning with Ruby best practices. While this appears to be a breaking change, there are no practical applications where Stoplight should handle such system-level errors (most of which were previously included in the default skip list anyway).
=> Limit Stoplight error tracking to StandardError exceptions

.github/workflows/ci.yml
It seems they removed this functionality and now only accept anonymous reports. This is the reason all cucumber builds fail now
=> Remove CUCUMBER_PUBLISH_TOKEN for anonymous reports

lib/stoplight.rb, lib/stoplight/config/config_provider.rb, lib/stoplight/config/user_default_config.rb, lib/stoplight/data_store/fail_safe.rb, lib/stoplight/default.rb, lib/stoplight/light.rb, lib/stoplight/light/config.rb, lib/stoplight/traffic_control/base.rb, spec/stoplight/config/config_provider_spec.rb, spec/stoplight/light/config_spec.rb, spec/stoplight/light/green_run_strategy_spec.rb, spec/stoplight/light/yellow_run_strategy_spec.rb
The current configuration system has several issues that lead to unpredictable behavior and potential bugs:
1. Configuration transformations (fail-safe wrapping, type conversions) were scattered across multiple locations. Some transformations happened in constructors, others in setters, making the system unpredictable
2. Data structure logic was intertwined with transformation logic in both `Light::Config` and `UserDefaultConfig`
This PR centralizes all configuration transformations into a single, idempotent pipeline within `ConfigProvider`:
* Move all transformations (fail-safe wrapping, type conversions, array normalization) to `ConfigProvider#transform_settings`
* Remove transformation logic from `Light::Config` constructor and `UserDefaultConfig` setters
* `light.with(**settings)` now …
=> Centralize Configuration Transformations

lib/stoplight/data_store/redis.rb, spec/stoplight/data_store/redis_spec.rb
This PR aims to fix an issue with Redis being unavailable during Stoplight initialization.
Sometimes we use an application to run tasks w/o a data layer (e.g., `rake assets: precompile`). However, Stoplight expects to have Redis available during initialization since [we upload Lua scripts](https://github.com/bolshakov/stoplight/blob/da05dcc380d2fe4d8c84d1f7e0cb98a82e4e9308/lib/stoplight/data_store/redis.rb#L79-L103) to it.
Now we lazily load scripts into Redis when we need them.
=> Fix: Do not raise error in initialization if Redis is unavailable

lib/stoplight/data_store/fail_safe.rb
This PR aims to stop sending reconfigure notifications for fail-safe, like [we do for notifiers](https://github.com/bolshakov/stoplight/blob/3e769f0f332c74d1d8acae1520805665f144ca51/lib/stoplight/notifier/fail_safe.rb#L62-L64).
Although later changes fix this problem, I'd like to hotfix it and release it with `v5.0.2` along with the lazy loading scripts SHAs in #357
=> Fix: Stop sending reconfigure notifications for fail safe

.github/workflows/ci.yml, .github/workflows/docker-build.yml
With [the rise of supply chain attacks], we want to harden our security. The first step is to ensure the integrity of GitHub workflows and to use minimal permissions. Step Security's [Harden Runner] was added to all workflows to sucure them and provide anomaly detection during builds. See an example of report here https://app.stepsecurity.io/github/bolshakov/stoplight/actions/runs/16589500642
[the rise of supply chain attacks]: https://arstechnica.com/security/2025/07/open-source-repositories-are-seeing-a-rash-of-supply-chain-attacks/
[Harden Runner]: https://github.com/step-security/harden-runner
=> Secure workflows with harden runner

.github/workflows/release.yml
* Do not require release approval from Docker build since it already depend on the gem build which requires approval
* Read docker tag from gempsec
=> Fix docker build

lib/stoplight/data_store/fail_safe.rb, lib/stoplight/empty_metadata.rb, lib/stoplight/metadata.rb, spec/stoplight/data_store/fail_safe_spec.rb, spec/stoplight/light/green_run_strategy_spec.rb
Fixes #413
Example scenario:
```ruby
redis = Redis.new(url: "redis://561922f7-6b30-49d3-8148-324922d590d2:6379/0")
light = Stoplight('bug-report-2025-08-22', data_store: Stoplight::DataStore::Redis.new(redis))
light.run { raise 'foo' }
```
It raises "foo" error. Before the fix, it exhibited unexpected behavior.
💡Fixing this, I realized we could behave better when the data store is failing. Currently, we protect the underlying Redis data store with an in-memory-based circuit breaker. While it works for protecting the Redis data store itself, when Redis itself fails, the protected service becomes unprotected. **We should think of how to switch to in-Memory data store for protecting the service in such situations**
=> Prevent Stoplight failures when Redis is not reachable

features/stoplight/step_definitions/assertions_steps.rb, lib/stoplight/light/yellow_run_strategy.rb, lib/stoplight/metadata.rb, lib/stoplight/traffic_recovery.rb, lib/stoplight/traffic_recovery/base.rb, lib/stoplight/traffic_recovery/consecutive_successes.rb, spec/stoplight/light/yellow_run_strategy_spec.rb, spec/stoplight/metadata_spec.rb, spec/stoplight/traffic_recovery/consecutive_successes_spec.rb
Fixes #426 
Fixes a race condition where multiple Stoplight instances could interfere with each other's recovery process. When one instance successfully completes recovery and clears the`recovery_started_at` timestamp, other instances would get `nil` and incorrectly determine circuit state.
Refactor traffic recovery to use dedicated decision types instead of reusing Color constants, improving type safety and semantic clarity.
- Add `TrafficRecovery::Decision` enum with GREEN, YELLOW, RED, PASS states
- Replace Color constants with TrafficRecovery decisions in recovery strategies
- Introduce PASS decision for the concurrent recovery completion scenariou
=> Handle concurrent recovery completion in consecutive successes strategy

.github/workflows/ci.yml, README.md
This PR aims to add DragonflyDB support for Stoplight.
Addresses #413 #414 #416 
After some consideration, I've decided not to commit to support `DragonflyDB`. However, I will list recommendations regarding a way to run Stoplight alongside DragonflyDB, and we can accept contributions to support `DragonflyDB` in the future 🙂
=> feat: Add DragonflyDB Support 

features/stoplight/traffic_control/consecutive_errors.feature, features/stoplight/traffic_control/error_rate.feature, lib/stoplight/data_store/fail_safe.rb, lib/stoplight/data_store/memory.rb, lib/stoplight/data_store/redis.rb, lib/stoplight/empty_metadata.rb, lib/stoplight/light.rb, lib/stoplight/light/green_run_strategy.rb, lib/stoplight/light/red_run_strategy.rb, lib/stoplight/light/run_strategy.rb, lib/stoplight/light/yellow_run_strategy.rb, lib/stoplight/metadata.rb, spec/dummy/bin/rails, spec/dummy/bin/rake, spec/properties/notifications_spec.rb, spec/stoplight/data_store/fail_safe_spec.rb, spec/stoplight/light/green_run_strategy_spec.rb, spec/stoplight/light/red_run_strategy_spec.rb, spec/stoplight/light/run_strategy_spec.rb, spec/stoplight/light/yellow_run_strategy_spec.rb, spec/stoplight/light_spec.rb, spec/stoplight/metadata_spec.rb, spec/stoplight/traffic_control/error_rate_spec.rb, spec/stoplight/traffic_recovery/consecutive_successes_spec.rb
Fixes #438 - Missing RED→YELLOW transition notifications
The issue was that time-based RED→YELLOW transitions (when `recovery_scheduled_after` expires) weren't sending notifications, breaking the deduplication logic and causing missing notifications in complex sequences.
- RED→YELLOW notifications now happen in `YellowRunStrategy#execute`, giving strategies access to full metadata context
- All run strategies now receive metadata to enable consistent transition handling  
- Made `current_time` a required parameter in `Metadata` constructor to eliminate race conditions where color calculations used different time contexts
- Use `Timecop.freeze` to ensure deterministic timing behavior
The fix ensures all automatic transitions trigger proper notifications, maintaining the notification chain …
=> Send notification about YELLOW color transitions

lib/stoplight/config/system_config.rb, lib/stoplight/data_store/fail_safe.rb, spec/stoplight/data_store/fail_safe_spec.rb
Previously, when the Redis data store became unavailable, Stoplight would return empty default values (`[]`, `{}`, `nil`) instead of maintaining circuit breaker functionality. This caused circuit breakers to appear functional but unable to track failures or transition states, leaving protected services vulnerable during Redis outages.
This PR changes this behaviour. When Redis becomes unavailable, automatically switch to in-memory data store to maintain full circuit breaker functionality.
Impact:
- Circuit breakers remain fully functional during Redis outages
- Protected services continue to be protected with proper failure tracking
- Zero-latency failover once circuit opens (no Redis timeout delays)
- Automatic recovery when Redis becomes available again
Closes #419
=> Implement automatic failover to in-memory data store when Redis unavailable

lib/stoplight/light/config.rb, spec/stoplight/light/config_spec.rb
We didn't run traffic recovery validation when instantiating a new or extending existing light which coul've caused an incompatible configuration and runtime failure.
Before the fix:
```ruby
> Stoplight("foo", traffic_recovery: :consecutive_successes, recovery_threshold: 0.25)
=> #<Stoplight::Light:0x0000000106740160
```
After the fix:
```ruby
Stoplight("foo", traffic_recovery: :consecutive_successes, recovery_threshold: 0.25)
stoplight/lib/stoplight/light/config.rb:104:in `block in validate_traffic_recovery_compatibility!': Stoplight::TrafficControl::ConsecutiveErrors strategy is incompatible with the Stoplight configuration: `recovery_threshold` should be an integer (Stoplight::Error::ConfigurationError)
from <internal:kernel>:124:in `then'
```
=> Validate traffic recovery compatibility when calling Light#with
