bolshakov/stoplight

lib/stoplight.rb
lib/stoplight/data_store/base.rb
lib/stoplight/data_store/memory.rb
lib/stoplight/data_store/redis.rb
lib/stoplight/failure.rb
lib/stoplight/light.rb
lib/stoplight/light/runnable.rb
lib/stoplight/notifier/base.rb
lib/stoplight/notifier/hip_chat.rb
lib/stoplight/notifier/io.rb

I believe that having a great README is the best kind of documentation. That being said, it's undeniably useful to see the types of methods. This pull request adds type-level documentation to all public methods. This should make it a lot easier to implement a custom data store, for instance.

Add documentation

---

README.md

I made this one myself. I took the colors from the Emoji One icon. Then I fixed the order of the lights.

Switch back to using a hosted SVG icon

---

lib/stoplight.rb
lib/stoplight/notifier/slack.rb
spec/stoplight/notifier/slack_spec.rb
stoplight.gemspec

Hey! 
My team uses Slack so I decided to extend Stoplight with another notifier. Does it look good to go?

Added slack notifier

---

README.md

Update misleading timeout documentation

---

.travis.yml

Use the new Travis CI infrastructure

---

README.md
lib/stoplight/default.rb
lib/stoplight/light.rb
lib/stoplight/light/runnable.rb
spec/stoplight/default_spec.rb
spec/stoplight/light/runnable_spec.rb
spec/stoplight/light_spec.rb

PR to address https://github.com/orgsync/stoplight/issues/88

Rename timeout to cool_off_time.

---

lib/stoplight.rb
lib/stoplight/notifier/raven.rb
spec/stoplight/notifier/raven_spec.rb
stoplight.gemspec

Similar to Honeybadger, would be nice to have Sentry/Raven notifier.

Add Sentry/Raven notifier

---

README.md
lib/stoplight.rb
lib/stoplight/notifier/rollbar.rb
spec/stoplight/notifier/rollbar_spec.rb

Here is the Rollbar documentation https://docs.rollbar.com/docs/plain-ruby

Add rollbar notifier

---

README.md
lib/stoplight.rb
lib/stoplight/notifier/pagerduty.rb
spec/stoplight/notifier/pagerduty_spec.rb
stoplight.gemspec

Adds support for notifying pagerduty any any stoplight changes. Happy to add anything else I may have missed!

Adds support for pagerduty notifications

---

README.md
lib/stoplight.rb
lib/stoplight/notifier/pagerduty.rb
stoplight.gemspec

They are alphabetically ordered now.

Reorder dependencies

---

.travis.yml

Test against laters rubies

---

README.md

Add stoplight-sentry

---

README.md

Update supported ruby version in ruby

---

bench/README.md
bench/data_store/memory/with_deduplicated_notification.rb
bench/data_store/redis/record_failure.rb
lib/stoplight/data_store/memory.rb
lib/stoplight/data_store/redis.rb
lib/stoplight/failure.rb
lib/stoplight/light/runnable.rb
spec/stoplight/config/config_provider_spec.rb
spec/support/light/runnable/run.rb

This PR implements several performance optimizations throughout the Stoplight library, with a focus on the data store implementation and light operations.
- Implemented Lua scripting for `record_failure` operations, reducing Redis round-trips
- Pre-load Lua scripts during initialization for faster subsequent executions
- Replaced `multi` with `pipelined` where appropriate for improved throughput
- Optimized `state` method to directly query data store for state without querien for failures 
- Added `cool_off_period_exceeded?` helper method to Failure class for cleaner code
- Simplified Stoplight initialization in the `safely` method
- Split synchronize blocks for better concurrency in `get_all`
#285

Performance Optimization: Data Store and Light Operations

---

README.md
lib/stoplight/light/config.rb
lib/stoplight/light/configurable.rb
lib/stoplight/light/lockable.rb
lib/stoplight/notifier/base.rb
lib/stoplight/notifier/generic.rb
spec/spec_helper.rb
spec/stoplight/light/configurable_spec.rb
spec/stoplight/light_spec.rb

This PR completely revises the Stoplight documentation and introduces the new `Light#with` method for easier configuration.
The PR introduces a new `Light#with` method that allows for bulk configuration of stoplights:
```ruby
base_api = Stoplight('api-service')
users_api = base_api.with(
threshold: 5,
cool_off_time: 30,
tracked_errors: [TimeoutError]
)
orders_api = base_api.with(
threshold: 10,
window_size: 300
)
```
This method offers several advantages:
- **Immutability**: Creates new instances without modifying the original stoplight
- **Composability**: Perfect for creating specialized stoplights from a common base configuration
- **Cleaner Syntax**: More concise than chaining multiple `.with_*` methods
- **Bulk Updates**: Update multiple settings at once with clear, readable code
The …

Improved Documentation and Code Examples

---

lib/stoplight/data_store/redis.rb
spec/stoplight/data_store/redis_spec.rb

Stoplight's distributed, leader-less architecture relies on time-based coordination for circuit breaker decisions. Clock skew between servers can cause inconsistent behavior:
- Different instances may see different error counts for the same time window
- Recovery timing coordination becomes unreliable
- Color transitions may occur at different times across the instances
This PR introduces automatic clock skew detection in the Redis Data Store:
* Probabilistic checking: Runs detection ~1% of the time to minimize performance impact
* Configurable warnings: Can be disabled via `warn_on_clock_skew: false` parameter
* Clear guidance: Warning messages link to wiki documentation
Example warning:
> Detected clock skew between Redis and the application server. Redis time: 1748277980, Application …

Implement clock skew detection

---

README.md

Add colors to state transition diagram

---

lib/stoplight/admin/views/layout.erb

Currently, our footer hangs in the middle of the page if we have only 1-2 lights. This PR aims to fix it.
Before:
After:

Chore: Adjust footer placement

---

README.md

Describe how to develop Stoplight

Add Development section to README

---

Gemfile.lock
lib/stoplight/version.rb

This PR bumps version for the latest hotfix #369

Stoplight 5.0.3 version fix

---

.github/dependabot.yml
.github/workflows/dependency-review.yml
.github/workflows/release.yml

This pull request is created by [StepSecurity](https://app.stepsecurity.io/securerepo) at the request of @bolshakov. Please merge the Pull Request to incorporate the requested changes. Please tag @bolshakov on your message if you have any questions related to the PR.
The GITHUB_TOKEN is an automatically generated secret to make authenticated calls to the GitHub API. GitHub recommends setting minimum token permissions for the GITHUB_TOKEN.
- [GitHub Security Guide](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow)
- [The Open Source Security Foundation (OpenSSF) Security Guide](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions)
With Dependabot version updates, when Dependabot identifies an …

[StepSecurity] Apply security best practices

---

lib/stoplight/data_store/redis/get_metadata.lua

Fix `get_metadata.lua` script error on DragonflyDB

---

README.md

Fix a few minor typos in the Readme file.

[ci skip] Fix typos in Readme
